name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Build binary
      run: go build -o bin/togo

    - name: Lint code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...
